version: "3.1"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      POSTGRES_DB: rebalancing
      TZ: America/Toronto
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5556:5432
    networks:
      - xbase

  rebalancing_migrate:
    build:
      context: .
      target: migrate
    depends_on:
      - postgres
    networks:
      - xbase
    env_file:
      - app.env

  rebalancing_svc:
    build:
      context: .
      target: api
    depends_on:
      - postgres
      - rebalancing_migrate
    ports:
      - 5051:5051
    networks:
      - xbase
    env_file:
      - app.env

networks:
  xbase:
    driver: bridge

volumes:
  db_data:
    driver: local
    name: rebalancing_db_data
